### ISSUE TITLE
Request change to Action: COBOL -> GnuCOBOL

### ISSUE THREAD

**Issue by spgennard** [fabasoad/setup-cobol-action#2]
**Action name should be specific**
The action name of COBOL should be GnuCOBOL to allow for other variants of COBOL to exist without people getting confused.

**Comment by fabasoad** [comment]
Thank you for this ticket. I would like to leave action name is as and actually, _GnuCOBOL_ is mentioned in _README_ ("Inputs" table) and in action description but it seems it's not enough, so anyway I will add _GnuCOBOL_ to the title and description of _README_ to avoid possible confusions in a future. Having it in a title shouldn't confuse people in a future.
